import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

export const outfit = Outfit({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-outfit", // IMPORTANT
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Link in bio tool: Everything you are, in one simple link | Linktree",
  description: "Generated by Hammad Mustafa",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} text-black font-sans antialiased`}>
            <Navbar/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
